// Generated by IB v0.3.1 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import "Stubs.h"

@implementation ParserError

@end


@implementation NSNotificationCenter

@end


@implementation NSURLRequest

@end


@implementation InvalidURLError

@end


@implementation InvalidFileError

@end


@implementation BubbleWrap

@end


@implementation BubbleWrap

@end


@implementation ValidationSpecificationError

@end


@implementation RecordInvalid

@end


@implementation Model

@end


@implementation PersistFileError

@end


@implementation RelationIsNilError

@end


@implementation AdapterNotFoundError

@end


@implementation RecordNotSaved

@end


@implementation Column

@end


@implementation ModelNotSetError

@end


@implementation FieldBindingMap

@end


@implementation String

@end


@implementation Inflector

@end


@implementation NilClass

@end


@implementation Array

@end


@implementation Hash

@end


@implementation Symbol

@end


@implementation Ansi

@end


@implementation Debug

@end


@implementation Module

@end


@implementation String

@end


@implementation PersistFileError

@end


@implementation VersionNumberError

@end


@implementation ArrayFinderQuery

@end


@implementation Constraint

@end


@implementation Stylesheet

@end


@implementation Stylesheet

@end


@implementation Stylesheet

@end


@implementation TransformLayer

@end


@implementation TransformView

@end


@implementation NSView

@end


@implementation NSViewController

@end


@implementation NSWindow

@end


@implementation NSWindowController

@end


@implementation TeacupWindowController

@end


@implementation DummyView

@end


@implementation DummyTableView

@end


@implementation DummyTableColumn

@end


@implementation DummyButton

@end


@implementation DummyScrollView

@end


@implementation DummyTextField

@end


@implementation DummyTextView

@end


@implementation DummyLayer

@end


@implementation Style

@end


@implementation Stylesheet

@end


@implementation Autoresize

@end


@implementation AppDelegate

@end


@implementation BaseWindowController

@end


@implementation Branch

@end


@implementation Command

@end


@implementation Commit

@end


@implementation Rebase

@end


@implementation MainWindowController

@end


@implementation AppDelegate

@end


@implementation Array

@end


@implementation NSObject

@end


@implementation NSPopover

@end


@implementation NSTableView

@end


@implementation NSTextField

@end


@implementation NSView

@end


@implementation ChooseBranchPopover

@end


@implementation CommitNode

@end


@implementation ContentInsetTableHeaderView

@end


@implementation NodeButton

@end


@implementation NodePopover

@end


@implementation TableDelegateProxy

@end



